/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estoque.view;

import com.mycompany.estoque.model.Produto;
import com.mycompany.estoque.repository.Conexao;
import com.mycompany.estoque.repository.ConexaoMySQL;
import com.mycompany.estoque.repository.ProdutoRepository;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class Edicao extends javax.swing.JFrame {
    
    private ProdutoRepository produtoRepository = new ProdutoRepository();
    private Connection connection;

    /**
     * Creates new form Edicao1
     */
    public Edicao() {
        initComponents();
        setLocationRelativeTo(null); //centralizar a pagina de cadastro
        configurarConexao();
        produtoRepository = new ProdutoRepository();
    }
    
    private void configurarConexao(){
        // Configurando a conexão com os dados do banco local
        Conexao conexao = new Conexao(
                "localhost",
                "root",
                "sua_senha_do_banco", //coloque sua senha do banco de dados
                3306,
                "estoque"
        );

        ConexaoMySQL conexaoMySQL = new ConexaoMySQL(conexao); //iniciando a com os dados do objeto conexao
        if (conexaoMySQL.conectar()) {  
            connection = ConexaoMySQL.connection;   //faz a conexão
        } else { 
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE); //mmensagem de erro
            return;  
        }
    }

    private void limparCampos() { //função para limpar os JLabels da página
        txtNome.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        txtQtda.setText("");
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        salvarEdicao = new javax.swing.JButton();
        txtLocalizarID = new javax.swing.JTextField();
        FecharTela = new javax.swing.JButton();
        buscarID = new javax.swing.JButton();
        txtQtda = new javax.swing.JTextField();
        excluirButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edição/Exclução");

        jLabel2.setText("Nome Produto");

        jLabel3.setText("Descrição");

        jLabel4.setText("Preço");

        jLabel5.setText("Qtda em Estoque");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Digite o ID do produto:");

        salvarEdicao.setBackground(new java.awt.Color(0, 255, 0));
        salvarEdicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salvarEdicao.setText("Salvar");
        salvarEdicao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salvarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarEdicaoSalvarEdicao(evt);
            }
        });

        FecharTela.setText("Fechar");
        FecharTela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FecharTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharTela(evt);
            }
        });

        buscarID.setText("Buscar");
        buscarID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDBuscarID(evt);
            }
        });

        excluirButton.setBackground(new java.awt.Color(255, 0, 0));
        excluirButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        excluirButton.setForeground(new java.awt.Color(255, 255, 255));
        excluirButton.setText("Excluir");
        excluirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 596, Short.MAX_VALUE)
                .addComponent(FecharTela)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalizarID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(55, 55, 55)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQtda, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salvarEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(excluirButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLocalizarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarID))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQtda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(salvarEdicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirButton)
                .addGap(31, 31, 31)
                .addComponent(FecharTela)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarEdicaoSalvarEdicao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarEdicaoSalvarEdicao
        try {
            // Criar o objeto produto com os dados preenchidos
            Produto produto = new Produto();
            produto.setId(Integer.parseInt(txtLocalizarID.getText()));
            produto.setNome(txtNome.getText());
            produto.setDescricao(txtDescricao.getText());
            produto.setPreco(Double.parseDouble(txtPreco.getText()));
            produto.setQuantidade(Integer.parseInt(txtQtda.getText()));

            // Etapa 1: Confirmação de atualização
            int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza de que deseja atualizar o produto com ID " + produto.getId() + "?",
                "Confirmação de Atualização",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (confirmacao == JOptionPane.YES_OPTION) {
                // Etapa 2: Atualizar o produto no banco de dados
                boolean sucesso = produtoRepository.atualizar(connection, produto);

                if (sucesso) {
                    // Etapa 3: Mensagem de sucesso
                    JOptionPane.showMessageDialog(
                        this,
                        "Produto com ID " + produto.getId() + " atualizado com sucesso!",
                        "Atualização Bem-Sucedida",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                } else {
                    // Etapa 4: Mensagem de falha
                    JOptionPane.showMessageDialog(
                        this,
                        "Não foi possível atualizar o produto com ID " + produto.getId() + ".",
                        "Erro na Atualização",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            } else {
                // Caso o usuário cancele a atualização
                JOptionPane.showMessageDialog(
                    this,
                    "A atualização foi cancelada pelo usuário.",
                    "Operação Cancelada",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro nos dados inseridos. Por favor, verifique os valores preenchidos.",   //mmensagem de erro
                "Erro de Entrada",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao tentar atualizar o produto: " + ex.getMessage(),   //mmensagem de erro
                "Erro",  
                JOptionPane.ERROR_MESSAGE
            );
        }
        
    }//GEN-LAST:event_salvarEdicaoSalvarEdicao

    private void FecharTela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharTela
        Inicio inicio = new Inicio();
        inicio.setVisible(true);    //fecha a tela de cadastro e inicia a tela inicial novamente
        dispose();
    }//GEN-LAST:event_FecharTela

    private void buscarIDBuscarID(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDBuscarID
        
        try{
            int id = Integer.parseInt(txtLocalizarID.getText()); //pega o id colocado pelo usuário
            
            Produto produto = produtoRepository.selecionar(connection, id);  //chama a função de selecionar os produtos, recebendo o id que o usuário colocou     
           
            if (produto != null) {
                // Preencher os campos com os dados do produto encontrado
                txtNome.setText(produto.getNome());
                txtDescricao.setText(produto.getDescricao());
                txtPreco.setText(String.valueOf(produto.getPreco()));
                txtQtda.setText(String.valueOf(produto.getQuantidade()));
            } else {
                // Caso o produto não seja encontrado
                JOptionPane.showMessageDialog(this, "Produto não encontrado!", "Erro", JOptionPane.WARNING_MESSAGE);
                limparCampos(); // Limpar os campos para evitar exibição de dados incorretos
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao buscar o produto: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
       
     
    }//GEN-LAST:event_buscarIDBuscarID

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        
        try {
            int id = Integer.parseInt(txtLocalizarID.getText()); //pega o id colocado pelo usuário

            // Etapa 1: Confirmação de exclusão
            int confirmacao = JOptionPane.showConfirmDialog(
                this, 
                "Tem certeza de que deseja excluir o produto com ID " + id + "?",
                "Confirmação de Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (confirmacao == JOptionPane.YES_OPTION) {
                // Etapa 2: Tentativa de exclusão
                boolean sucesso = produtoRepository.deletar(connection, id);

                if (sucesso) {
                    // Etapa 3: Mensagem de sucesso
                    JOptionPane.showMessageDialog(
                        this,
                        "Produto com ID " + id + " foi excluído com sucesso!",
                        "Exclusão Bem-Sucedida",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    limparCampos(); // Limpa os campos após exclusão
                } else {
                    // Etapa 4: Mensagem de falha
                    JOptionPane.showMessageDialog(
                        this,
                        "Produto com ID " + id + " não foi encontrado ou não pôde ser excluído.",
                        "Erro na Exclusão",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            } else {
                // Caso o usuário cancele a exclusão
                JOptionPane.showMessageDialog(
                    this,
                    "A exclusão foi cancelada pelo usuário.",
                    "Operação Cancelada",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                this,
                "ID inválido. Por favor, insira um número válido.", //mensagem de erro
                "Erro de Entrada",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao tentar excluir o produto: " + ex.getMessage(),  //mensagem de erro
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_excluirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FecharTela;
    private javax.swing.JButton buscarID;
    private javax.swing.JButton excluirButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton salvarEdicao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtLocalizarID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtda;
    // End of variables declaration//GEN-END:variables
}
